import src.environment as environment
from gym.utils.play import play

def test_environment_play():
    env = environment.MontezumaEnvironment(render="rgb_array")
    env.reset()
    play(env, zoom=5, fps=15)
    env.close()

def test_environment_lives():
    env = environment.MontezumaEnvironment(render_mode="rgb_array")
    env.reset()
    env.display_frame_stack()
    print(env.lives)
    env.close()


def test_environment_action():
    env = environment.MontezumaEnvironment(render_mode="rgb_array")
    env.reset()
    print(env.get_agent_position())
    
    env.step(14)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(14)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(3)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(5)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    # x=105, y=148 En bas du niveau
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(15)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    # (39, 148) Après la tete de mort
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(4)
    env.step(2)
    env.step(2)
    env.step(2)
    env.step(2)
    env.step(2)
    env.step(2)
    env.step(2)
    env.step(2)
    env.step(2)
    # (21, 192) Devant la clé en haut de l'echelle


    #env.set_agent_position(105,148)
    #env.step(4)
    print(env.get_agent_position())

    env.display_frame_stack()
    print(env.lives)
    env.close()

if __name__ == "__main__":
    test_environment_lives()